# Generated by Django 5.1.4 on 2024-12-17 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DropoutData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('social_category', models.CharField(choices=[('SC', 'Sc'), ('ST', 'St'), ('OBC', 'Obc'), ('General', 'General')], default='General', max_length=10)),
                ('year_end', models.IntegerField()),
                ('primary_girls', models.FloatField()),
                ('primary_boys', models.FloatField()),
                ('primary_overall', models.FloatField()),
                ('upper_primary_girls', models.FloatField()),
                ('upper_primary_boys', models.FloatField()),
                ('upper_primary_overall', models.FloatField()),
                ('secondary_girls', models.FloatField()),
                ('secondary_boys', models.FloatField()),
                ('secondary_overall', models.FloatField()),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drop_0.state')),
            ],
        ),
    ]
